"""create initial tables

Revision ID: ba4b3fcb64ec
Revises: 
Create Date: 2026-09-28 01:57:47.062125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4b3fcb64ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('poi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('avg_duration_min', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_poi_city_id_city')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi')),
    sa.UniqueConstraint('place_id', name=op.f('uq_poi_place_id'))
    )
    op.create_index(op.f('ix_poi_city_id'), 'poi', ['city_id'], unique=False)
    op.create_table('saved_route',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('accommodation_lat', sa.Float(), nullable=False),
    sa.Column('accommodation_lng', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_saved_route_city_id_city')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_saved_route_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_route'))
    )
    op.create_index(op.f('ix_saved_route_user_id'), 'saved_route', ['user_id'], unique=False)
    op.create_table('route_stop',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('saved_route_id', sa.String(), nullable=False),
    sa.Column('poi_id', sa.String(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], name=op.f('fk_route_stop_poi_id_poi')),
    sa.ForeignKeyConstraint(['saved_route_id'], ['saved_route.id'], name=op.f('fk_route_stop_saved_route_id_saved_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stop'))
    )
    op.create_index(op.f('ix_route_stop_saved_route_id'), 'route_stop', ['saved_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stop_saved_route_id'), table_name='route_stop')
    op.drop_table('route_stop')
    op.drop_index(op.f('ix_saved_route_user_id'), table_name='saved_route')
    op.drop_table('saved_route')
    op.drop_index(op.f('ix_poi_city_id'), table_name='poi')
    op.drop_table('poi')
    op.drop_table('user')
    op.drop_table('city')
    # ### end Alembic commands ###
