"""add poi rating columns

Revision ID: ea442a596b1a
Revises: ba4b3fcb64ec
Create Date: 2026-09-28 03:01:31.742078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea442a596b1a'
down_revision: Union[str, Sequence[str], None] = 'ba4b3fcb64ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('poi', sa.Column('user_rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'user_rating_count')
    op.drop_column('poi', 'rating')
    # ### end Alembic commands ###
