"""add saved route snapshot and user created_at

Revision ID: 7f7326cabac4
Revises: ea442a596b1a
Create Date: 2026-09-28 23:23:48.903677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7326cabac4'
down_revision: Union[str, Sequence[str], None] = 'ea442a596b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_route', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('saved_route', sa.Column('travel_mode', sa.String(length=10), nullable=False))
    op.add_column('saved_route', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('saved_route', 'plan')
    op.drop_column('saved_route', 'travel_mode')
    op.drop_column('saved_route', 'name')
    # ### end Alembic commands ###
